site_name: ğŸ«– Introduction to 3D Software  
site_url: https://3dsoftware.vinnyroca.info/

nav:
  - ğŸ“‹Syllabus : index.md
  - ğŸ“†Schedule : schedule.md
  - ğŸ’»Notes :
    - Notes Index: Notes/notes.md
    - 1. Maya Interface and Objects: 1_MayaInterface.md
    # - 2. Polygonal Modeling: 2_ModellingEssentials.md
    # - 3. Subdivision Modeling: 3_SubdivisionModeling.md
  - ğŸ“šExercises:
    - Exercise Index: Exercises/exerciseindex.md
    - In-class:
      - 1a.Simple Chair: Exercises/01_simplechair.md
      - 1b.Snapping Chair: Exercises/01_snappingchair.md
      # - 2a.Complete a Cube: Exercises/02_completeacube.md
      # - 2b.Archway: Exercises/02_archway.md
      # - 3a.Dice: Exercises/03_dice.md
      # - 3b.Teapot: Exercises/03_teapot.md
    - Independent:
      - 0. Computer Dreams: Exercises/00_computerdreams.md
      - 1.Creature: Exercises/01_creature.md
      # - 2.Tree: Exercises/02_tree.md
  - ğŸŒProjects :
    - Dream Object: dreamobject.md
    - Memory Chambre: memorypalace.md
  - ğŸ“–Responses :
    - Software Studies: Responses/SoftwareStudies.md
    - Media Archaeology 1: Responses/MediaArchaeology1.md
    - Media Archaeology 2: Responses/MediaArchaeology2.md
    - Media Archaeology 3: Responses/MediaArchaeology3.md
    - Cultural Studies: Responses/CulturalStudies.md
  - ğŸ–ï¸Artists : 
    - Rebecca Allen: Artists/allen.md
    - Karl Sims: Artists/sims.md
    - Char Davies: Artists/davies.md
    - Jennifer Steinkamp: Artists/steinkamp.md
  


  

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      title: On this page
      toc_depth: 2

theme:
  icon:
    logo: material/cube
  name: material
  highlightjs: true
  palette:
    scheme: default
    primary: white
    accent: black
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant: false
  font:
    text: Funnel Sans
    code: Inconsolata monospace
plugins:
  - search:
      enabled: true


extra_css:
- extra.css


  



  



